name: Generate Snake

on:
  # 每天午夜自动运行
  schedule:
    - cron: "0 0 * * *" 
  # 允许手动强制运行
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ClaireBaii
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#196127&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39&color_legend=false
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#196127&color_legend=false

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
